// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package seamoor

import (
	"seamoor/ent/user"
)

type CreateUserInput struct {
	Name     string    `json:"name"`
	Surname  string    `json:"surname"`
	Position string    `json:"position"`
	Email    string    `json:"email"`
	Role     user.Role `json:"role"`
}

type Credential struct {
	AccessToken string `json:"accessToken"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
