package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"ginent"
	"ginent/ent"
	"ginent/feature/todo"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input ent.CreateTodoInput) (*ent.Todo, error) {
	return todo.CreateTodo(&ctx, r.client, &input) //
}

// Mutation returns ginent.MutationResolver implementation.
func (r *Resolver) Mutation() ginent.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
