package controller

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/pumy2517/ginent/ent"
)

// CreateTest01 is the resolver for the createTest01 field.
func (r *mutationResolver) CreateTest01(ctx context.Context, input ent.CreateTest01Input) (*ent.Test01, error) {
	panic(fmt.Errorf("not implemented: CreateTest01 - createTest01"))
}
