package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"
	"ginent"
	"ginent/ent"
	"ginent/services"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input ent.CreateTodoInput) (*ent.Todo, error) {
	return services.CreateTodo(&ctx, r.client, &input)
}

// GetTodoEiei is the resolver for the getTodoEiei field.
func (r *queryResolver) GetTodoEiei(ctx context.Context) ([]*ent.Todo, error) {
	panic(fmt.Errorf("not implemented: GetTodoEiei - getTodoEiei"))
}

// Mutation returns ginent.MutationResolver implementation.
func (r *Resolver) Mutation() ginent.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
