// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Test01 is the predicate function for test01 builders.
type Test01 func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
